In [1]:
import time
import numpy as np
ticks=time.time()
localtime=time.localtime(ticks)
print(localtime)

time.struct_time(tm_year=2019, tm_mon=5, tm_mday=2, tm_hour=10, tm_min=34, tm_sec=58, tm_wday=3, tm_yday=122, tm_isdst=0)


In [2]:
fh=open("DataAnalyse/affinity_dataset.txt","r")
x=fh.read()
fh.close()

FileNotFoundError: [Errno 2] No such file or directory: 'DataAnalyse/affinity_dataset.txt'

In [3]:
a=list(range(12))
b=range(12)
c=[]
a[2]=12   
    
print(a)

[0, 1, 12, 3, 4, 5, 6, 7, 8, 9, 10, 11]


In [40]:
a=np.array([range(10),range(10)])
print(a)

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]


In [49]:
from numpy.random import randn
x=randn(7,7)
print(x[1])

[-0.72836747 -0.36807634 -0.46895465  0.51540329  0.47680205  0.10342807
 -2.72005845]


In [5]:
import numpy as np
a=[[1,2,3,4,5,6],[4,5,6,7,8,9]]
b=[[1,2],[2,3],[3,4],[4,5],[5,6],[7,8]]
r=[[0,1,0,0],
   [1,0,1,0],
   [0,0,0,1],
   [0,0,0,0]
]
r2=np.dot(r,r)#矩阵乘法
r3=np.dot(r2,r)
r4=np.dot(r3,r)
print(r)
print(r2)
print(r3)
print(r4)

[[0, 1, 0, 0], [1, 0, 1, 0], [0, 0, 0, 1], [0, 0, 0, 0]]
[[1 0 1 0]
 [0 1 0 1]
 [0 0 0 0]
 [0 0 0 0]]
[[0 1 0 1]
 [1 0 1 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 0 1 0]
 [0 1 0 1]
 [0 0 0 0]
 [0 0 0 0]]


In [1]:
import pandas as pd
import numpy as np
s= pd.Series([-12,-34,90,34],index=['e','f','g','h'])
print(s)
print(np.arange(10,15))
seq1 = pd.Series(np.array([3.45,1.67,5.56,7.89,9.01]),index=np.arange(1,6))
seq2 = pd.Series(np.arange(5,10),index=np.arange(1,6))
print(seq1,'\n',seq2,'\n')
print("协方差：",'\t',seq1.cov(seq2))
print("相关系数：",seq1.corr(seq2))
print("="*30)




e   -12
f   -34
g    90
h    34
dtype: int64
[10 11 12 13 14]
1    3.45
2    1.67
3    5.56
4    7.89
5    9.01
dtype: float64 
 1    5
2    6
3    7
4    8
5    9
dtype: int32 



协方差： 	 4.335
相关系数： 0.902611941976


In [2]:
#计算dataFrame结构数据的协方差以及相关系数
frame = pd.DataFrame([[1,4,5,6],[8.9,12.6,19.98,33.87],[23.11,34.56,22.45,19.987],[-23.1,90.7,34.6,89.4]],index=['a','b','c','d'],columns=['d1','d2','d3','d4'])
print(frame)
print("相关系数：",'\n',frame.corr())
print("协方差：",'\n',frame.cov())

      d1     d2     d3      d4
a   1.00   4.00   5.00   6.000
b   8.90  12.60  19.98  33.870
c  23.11  34.56  22.45  19.987
d -23.10  90.70  34.60  89.400
相关系数： 
           d1        d2        d3        d4
d1  1.000000 -0.676469 -0.426407 -0.785193
d2 -0.676469  1.000000  0.897642  0.925333
d3 -0.426407  0.897642  1.000000  0.891530
d4 -0.785193  0.925333  0.891530  1.000000
协方差： 
             d1           d2          d3           d4
d1  374.446692  -510.602183 -100.282608  -555.193883
d2 -510.602183  1521.526233  425.548683  1318.897738
d3 -100.282608   425.548683  147.710892   395.927608
d4 -555.193883  1318.897738  395.927608  1335.201352


In [3]:
#Series等级索引和分级
ser = pd.Series(np.random.rand(8),index=[['white','white','white','blue','blue','red','red','red'],['up','down','right','up','down','up','down','right']])
print('等级索引案例:','\n',ser)
print(ser.index)
print('\n',ser['white'])
#选取某个等级的子等级
print(ser['white','up'])
#调整形状==返回一个Series对象
print(ser.unstack())
#生成一个dataFrame对象,(通过series对象)
ser_01 = ser.unstack()
frame = pd.DataFrame(ser_01)
print(frame)
#如果想在吧dataFrame对象转换为Series对象,可使用series.stack()方法实现
ser_02 = frame.stack()
print(ser_02)

等级索引案例: 
 white  up       0.581036
       down     0.732923
       right    0.842040
blue   up       0.920236
       down     0.887100
red    up       0.645791
       down     0.073538
       right    0.385299
dtype: float64
MultiIndex(levels=[['blue', 'red', 'white'], ['down', 'right', 'up']],
           labels=[[2, 2, 2, 0, 0, 1, 1, 1], [2, 0, 1, 2, 0, 2, 0, 1]])

 up       0.581036
down     0.732923
right    0.842040
dtype: float64
0.581036450679
           down     right        up
blue   0.887100       NaN  0.920236
red    0.073538  0.385299  0.645791
white  0.732923  0.842040  0.581036
           down     right        up
blue   0.887100       NaN  0.920236
red    0.073538  0.385299  0.645791
white  0.732923  0.842040  0.581036
blue   down     0.887100
       up       0.920236
red    down     0.073538
       right    0.385299
       up       0.645791
white  down     0.732923
       right    0.842040
       up       0.581036
dtype: float64
